# Generated by Django 4.2.16 on 2024-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('traite', 'Traitée'), ('en_cours', 'En cours'), ('rejeté', 'Rejété')], default='en_attente', max_length=30),
        ),
    ]
