# Generated by Django 4.2.16 on 2024-12-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_alter_reclamation_statut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfert',
        ),
    ]
