# Generated by Django 4.2.16 on 2024-12-31 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_alter_etudiant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='sujet',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
