# Generated by Django 4.2.16 on 2024-12-31 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_reclamation_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='reponse',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
