# Generated by Django 4.2.16 on 2024-12-31 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_messagerie_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiant.departement'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiant.filiere'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_de_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiant.niveau'),
        ),
    ]
